Team-return/JOBIS-DSM-iOS-v2

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/CompanyInfoDetailResponseDTO.swift, Projects/Data/Sources/DTO/CompanyListResponseDTO.swift, Projects/Data/Sources/DTO/WritableReviewListResponseDTO.swift, Projects/Data/Sources/DataSource/API/CompaniesAPI.swift, Projects/Data/Sources/DataSource/Remote/CompaniesRemote.swift, Projects/Data/Sources/Repositories/CompaniesRepositoryImpl.swift, Projects/Domain/Sources/Entities/CompanyEntity.swift, Projects/Domain/Sources/Entities/CompanyInfoDetailEntity.swift, Projects/Domain/Sources/Entities/WritableReviewCompanyEntity.swift, Projects/Domain/Sources/Repositories/CompaniesRepository.swift, Projects/Domain/Sources/UseCases/Companies/FetchCompanyInfoDetailUseCase.swift, Projects/Domain/Sources/UseCases/Companies/FetchCompanyListUseCase.swift, Projects/Domain/Sources/UseCases/Companies/FetchWritableReviewListUseCase.swift
- Companies API
- Companies API
- Remote
- Repository
- UseCase
- FetchWritableReviewListUseCase
- FetchCompanyInfoDetailUseCase
- FetchCompanyListUseCase
=> merge :: (#7) Companies API

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/StudentInfoResponseDTO.swift, Projects/Data/Sources/DataSource/API/StudentsAPI.swift, Projects/Data/Sources/DataSource/Remote/StudentsRemote.swift, Projects/Data/Sources/Repositories/StudentsRepositoryImpl.swift, Projects/Domain/Sources/Entites/StudentInfoEntity.swift, Projects/Domain/Sources/Enums/DepartmentType.swift, Projects/Domain/Sources/Enums/GenderType.swift, Projects/Domain/Sources/Parameters/ChangePasswordRequestQuery.swift, Projects/Domain/Sources/Parameters/RenewalPasswordRequestQuery.swift, Projects/Domain/Sources/Parameters/SignupRequestQuery.swift, Projects/Domain/Sources/Repositories/StudentsRepository.swift, Projects/Domain/Sources/UseCases/Students/ChangePasswordUseCase.swift, Projects/Domain/Sources/UseCases/Students/ChangeProfileImageUseCase.swift, Projects/Domain/Sources/UseCases/Students/CompareCurrentPassswordUseCase.swift, Projects/Domain/Sources/UseCases/Students/FetchStudentInfoUseCase.swift, Projects/Domain/Sources/UseCases/Students/RenewalPasswordUseCase.swift, Projects/Domain/Sources/UseCases/Students/SignupUseCase.swift, Projects/Domain/Sources/UseCases/Students/StudentExistsUseCase.swift
=> merge :: (#6) Students API

Projects/Data/Sources/DTO/AuthTokenResponseDTO.swift, Projects/Data/Sources/DTO/CompanyInfoDetailResponseDTO.swift, Projects/Data/Sources/DTO/CompanyListResponseDTO.swift, Projects/Data/Sources/DTO/StudentInfoResponseDTO.swift, Projects/Data/Sources/DTO/WritableReviewListResponseDTO.swift
=> merge :: (#8) DTO public -> internal

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/Bugs/BugDetailResponseDTO.swift, Projects/Data/Sources/DTO/Bugs/BugListResponseDTO.swift, Projects/Data/Sources/DataSource/API/BugsAPI.swift, Projects/Data/Sources/DataSource/Remote/AuthRemote.swift, Projects/Data/Sources/DataSource/Remote/BugsRemote.swift, Projects/Data/Sources/DataSource/Remote/CompaniesRemote.swift, Projects/Data/Sources/DataSource/Remote/ReviewsRemote.swift, Projects/Data/Sources/DataSource/Remote/StudentsRemote.swift, Projects/Data/Sources/DataSource/Remote/UsersRemote.swift, Projects/Data/Sources/Repositories/BugsRepositoryImpl.swift, Projects/Data/Sources/Repositories/ReviewsRepositoryImpl.swift, Projects/Domain/Sources/Entities/Entity/BugDetailEntity.swift, Projects/Domain/Sources/Entities/Entity/BugEntity.swift, Projects/Domain/Sources/Enums/DevelopmentType.swift, Projects/Domain/Sources/Parameters/Bugs/ReportBugRequestQuery.swift, Projects/Domain/Sources/Repositories/BugsRepository.swift, Projects/Domain/Sources/UseCases/Bugs/FetchBugDetailUseCase.swift, Projects/Domain/Sources/UseCases/Bugs/FetchBugListUseCase.swift, Projects/Domain/Sources/UseCases/Bugs/ReportBugUseCase.swift
=> merge :: (#16) bugs api

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/Files/UploadFilesResponseDTO.swift, Projects/Data/Sources/DataSource/API/FilesAPI.swift, Projects/Data/Sources/DataSource/Remote/FilesRemote.swift, Projects/Data/Sources/Repositories/FilesRepositoryImpl.swift, Projects/Domain/Sources/Repositories/FilesRepository.swift, Projects/Domain/Sources/UseCases/Files/UploadFilesUseCase.swift
=> merge :: (#20) Files API

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/Applications/ApplicationListResponseDTO.swift, Projects/Data/Sources/DTO/Applications/AttachmentsResponseDTO.swift, Projects/Data/Sources/DTO/Applications/TotalPassStudentResponseDTO.swift, Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift, Projects/Data/Sources/DataSource/Remote/ApplicationsRemote.swift, Projects/Data/Sources/Repositories/ApplicationsRepositoryImpl.swift, Projects/Domain/Sources/Entities/Applications/ApplicationEntity.swift, Projects/Domain/Sources/Entities/Applications/AttachmentsEntity.swift, Projects/Domain/Sources/Entities/Applications/TotalPassStudentEntity.swift, Projects/Domain/Sources/Enums/ApplicationStatusType.swift, Projects/Domain/Sources/Enums/AttachmentType.swift, Projects/Domain/Sources/Parameters/Applications/ApplyCompanyRequestQuery.swift, Projects/Domain/Sources/Repositories/ApplicationsRepository.swift, Projects/Domain/Sources/UseCases/Applications/ApplyCompanyUseCase.swift, Projects/Domain/Sources/UseCases/Applications/CancelApplyUseCase.swift, Projects/Domain/Sources/UseCases/Applications/FetchApplicationUseCase.swift, Projects/Domain/Sources/UseCases/Applications/FetchTotalPassStudentUseCase.swift
=> marge :: (#5) Applications API

README.md
=> merge :: Update README.md

Projects/Data/Sources/DTO/Recruitments/AreaResponseDTO.swift, Projects/Data/Sources/DTO/Recruitments/RecruitmentDetailResponseDTO.swift, Projects/Domain/Sources/Entities/Recruitments/AreaEntity.swift, Projects/Domain/Sources/Entities/Recruitments/RecruitmentDetailEntity.swift
=> merge :: (#32) Recruitment ResponseDTO and Entity 수정

Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/Applications/FetchRejectionReasonResponseDTO.swift, Projects/Data/Sources/DTO/Recruitments/RecruitmentListResponseDTO.swift, Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift, Projects/Data/Sources/DataSource/Remote/RemoteApplicationsDataSource.swift, Projects/Data/Sources/Repositories/ApplicationsRepositoryImpl.swift, Projects/Domain/Sources/Entities/Recruitments/RecruitmentEntity.swift, Projects/Domain/Sources/Enums/ApplicationStatusType.swift, Projects/Domain/Sources/Repositories/ApplicationsRepository.swift, Projects/Domain/Sources/UseCases/Applications/ApplyCompanyUseCase.swift, Projects/Domain/Sources/UseCases/Applications/CancelApplyUseCase.swift, Projects/Domain/Sources/UseCases/Applications/FetchApplicationUseCase.swift, Projects/Domain/Sources/UseCases/Applications/FetchRejectionReasonUseCase.swift, Projects/Domain/Sources/UseCases/Applications/FetchTotalPassStudentUseCase.swift, Projects/Domain/Sources/UseCases/Applications/ReApplyCompanyUseCase.swift
ReApply API 추가했어요
ReApply API 추가
반려사유 받아오는 API 추가
Application -> Applications 오타 수정
지원상태 추가
Recruitment Response 수정 되서 맞춰 수정
=> merge :: (#60) ReApply API

Projects/Data/Sources/DataSource/API/BookmarksAPI.swift, Projects/Data/Sources/DataSource/API/BugsAPI.swift, Projects/Data/Sources/DataSource/API/ReviewsAPI.swift
=> merge :: (#65) API path 뒤 슬레쉬('/') 제거

Projects/Core/Sources/Steps/AlarmStep.swift, Projects/Core/Sources/Steps/HomeStep.swift, Projects/Core/Sources/Steps/MainStep.swift, Projects/Flow/Sources/Tabs/Home/AlarmFlow.swift, Projects/Flow/Sources/Tabs/Home/HomeFlow.swift, Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+setTitle .swift, Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+tabbar.swift, Projects/Presentation/Sources/Base/BaseTabBarController.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift, Projects/Presentation/Sources/Home/Alarm/AlarmViewModel.swift, Projects/Presentation/Sources/Home/Alarm/Cell/AlarmCell.swift, Projects/Presentation/Sources/Home/HomeViewController.swift, Projects/Presentation/Sources/Home/HomeViewModel.swift
=> 🔗 :: (#78) 알람 뷰 퍼블리싱

Projects/Data/Sources/DataSource/API/AuthAPI.swift, Projects/Domain/Sources/Parameters/Students/SignupRequestQuery.swift, Projects/Domain/Sources/Parameters/Users/SigninRequestQuery.swift
=> 🔗 :: (#100) 로그인, 토큰재발급, 회원가입에 platformType 추가

Projects/Modules/DesignSystem/Sources/Button/JobisButton.swift, Projects/Modules/DesignSystem/Sources/Extensions/UIImage/UIImage+resize.swift, Projects/Modules/DesignSystem/Sources/KF/KF+setJobisImage.swift, Projects/Modules/DesignSystem/Sources/Toast/JobisToast.swift, Projects/Presentation/Sources/Home/Components/CareerNavigationCard.swift, Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusTableViewCell.swift, Projects/Presentation/Sources/Home/Components/EmploymentView.swift, Projects/Presentation/Sources/Home/HomeViewController.swift, Projects/Presentation/Sources/MyPage/Components/Cell/ReviewNavigateView.swift, Projects/Presentation/Sources/MyPage/Components/SectionView.swift, Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift, Projects/Presentation/Sources/Recruitment/RecruitmentTableViewCell.swift
=> 🔗 :: (#79) Image Resize 함수 사용 정리

Projects/Domain/Sources/Entities/Applications/TotalPassStudentEntity.swift
>  totalStudentCount가 0일 때 1로 처리
=> 🔗 :: (#106) totalStudentCount가 0일 때 1로 처리

Projects/Modules/DesignSystem/Sources/TextField/Component/DescriptionView.swift, Projects/Presentation/Sources/MyPage/Components/SectionView.swift, Projects/Presentation/Sources/MyPage/MyPageViewController.swift, Projects/Presentation/Sources/Signin/SigninViewController.swift
> 로그인, 마이페이지 캡슐화
- 로그인, 마이페이지에 안되어 있던 캡슐화 진행
=> 🔗 :: (#74) 로그인, 마이페이지 캡슐화

Projects/Core/Sources/Steps/MyPageStep.swift, Projects/Core/Sources/Steps/TabsStep.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Flow/Sources/Tabs/MyPageFlow.swift, Projects/Flow/Sources/Tabs/TabsFlow.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Home/HomeViewModel.swift, Projects/Presentation/Sources/MyPage/Components/Cell/SectionCollectionViewCell.swift, Projects/Presentation/Sources/MyPage/MyPageViewController.swift, Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
> 로그아웃, 회원 탈퇴
- 마이페이지에 로그아웃, 회원 탈퇴 cell 클릭시 -> 애니메이션와 함께 Onboarding으로 이동
=> 🔗 :: (#102) 로그아웃, 회원탈퇴 구현

Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift, Projects/Presentation/Sources/MyPage/Components/BugSectionView.swift, Projects/Presentation/Sources/MyPage/Components/SectionView.swift, Projects/Presentation/Sources/MyPage/MyPageViewController.swift
=> 🔗 :: (#108) 마이페이지 Section 리팩토링

Projects/Modules/DesignSystem/Sources/Label/JobisMenuLabel.swift, Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift, Projects/Presentation/Sources/MyPage/Components/BugSectionView.swift, Projects/Presentation/Sources/MyPage/Components/SectionView.swift
=> 🔗 :: (#115) SectionView 리팩토링

Projects/Presentation/Sources/Base/BaseView.swift
>  BaseView 함수 호출 위치 변경
- init() 에 있던 addView(), setLayout() 위치를 layoutSubviews()로 변경
=> 🔗 :: (#117) 함수 호출 위치 변경

Projects/Presentation/Sources/Base/BaseTabBarController.swift
=> 🔗 :: (#126) Haptic 추가

Projects/Presentation/Sources/Base/BaseCollectionViewCell.swift, Projects/Presentation/Sources/Base/BaseTabBarController.swift, Projects/Presentation/Sources/Home/Components/BannerView.swift, Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift, Projects/Presentation/Sources/Home/Components/Cell/EmploymentCollectionViewCell.swift
> BaseCollectionViewCell 추가 
- BaseCollectionViewCell 추가 및 기존 코드 변경
=> 🔗 :: (#124) BaseCollectionViewCell

Projects/Modules/DesignSystem/Sources/Extensions/UILabel/UILabel+setJobisText.swift
=> 🔗 :: UILabel 말줄임 추가

Projects/Data/Sources/DTO/Recruitments/RecruitmentDetailResponseDTO.swift, Projects/Domain/Sources/Entities/Recruitments/RecruitmentDetailEntity.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewController.swift, Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewModel.swift, Projects/Presentation/Sources/Recruitment/RecruitmentList/RecruitmentViewController.swift
> 모집 의뢰서 Detail API 연동
> 
- 모집 의뢰서 Detail API 연동
=> 🔗 :: (#149) recruitmentDetail API 연동

Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
=> 🔗 :: (#162) fcm bug 수정

Projects/Core/Sources/Steps/ChangePasswordStep.swift, Projects/Core/Sources/Steps/ConfirmPasswordStep.swift, Projects/Core/Sources/Steps/MyPageStep.swift, Projects/Flow/Sources/ChangePassword/ChangePasswordFlow.swift, Projects/Flow/Sources/ChangePassword/ConfirmPasswordFlow.swift, Projects/Flow/Sources/MyPage/MyPageFlow.swift, Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+tabbar.swift, Projects/Presentation/Sources/ChangePassword/ChangePasswordViewController.swift, Projects/Presentation/Sources/ChangePassword/ChangePasswordViewModel.swift, Projects/Presentation/Sources/ConfirmPassword/ConfirmPasswordViewController.swift, Projects/Presentation/Sources/ConfirmPassword/ConfirmPasswordViewModel.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/MyPage/MyPageViewController.swift, Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
=> 🔗 :: (#166) Password 변경 퍼블리싱 & API

Projects/Core/Sources/Steps/BookmarkStep.swift, Projects/Data/Sources/DTO/Bookmarks/BookmarkResponseDTO.swift, Projects/Domain/Sources/Entities/Bookmarks/BookmarkEntity.swift, Projects/Flow/Sources/BookmarkFlow.swift, Projects/Presentation/Sources/Bookmark/BookmarkViewController.swift, Projects/Presentation/Sources/Bookmark/BookmarkViewModel.swift, Projects/Presentation/Sources/Bookmark/Cell/BookmarkTableViewCell.swift, Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusTableViewCell.swift, Projects/Presentation/Sources/Home/HomeViewController.swift, Projects/Presentation/Sources/MyPage/Components/Cell/SectionTableViewCell.swift, Projects/Presentation/Sources/Notice/Cell/AttachedFileTableViewCell.swift
> 북마크 클릭시 모집의뢰서 상세보기
- 북마크 클릭시 모집의뢰서 상세보기
=> 🧩 :: (#170) 북마크 클릭시 모집의뢰서 상세보기

Projects/Presentation/Sources/Signup/ProfileSetting/Components/LaterButton.swift, Projects/Presentation/Sources/Signup/ProfileSetting/ProfileSettingViewController.swift, Projects/Presentation/Sources/Signup/ProfileSetting/ProfileSettingViewModel.swift
=> 🔗 :: (#175) 다음에 하기 버튼 추가

Projects/Data/Sources/DTO/Recruitments/AreaResponseDTO.swift, Projects/Data/Sources/DTO/Recruitments/JobResponseDTO.swift, Projects/Data/Sources/DTO/Recruitments/TechReponseDTO.swift
=> 🔗 :: (#184) 모집의뢰서 상세보기 response 수정

Projects/Core/Sources/Steps/CompanySearchStep.swift, Projects/Core/Sources/Steps/HomeStep.swift, Projects/Domain/Sources/UseCases/Companies/FetchCompanyListUseCase.swift, Projects/Flow/Sources/Company/CompanySearchFlow.swift, Projects/Flow/Sources/Home/HomeFlow.swift, Projects/Presentation/Sources/CompanySearch/CompanySearchViewController.swift, Projects/Presentation/Sources/CompanySearch/CompanySearchViewModel.swift, Projects/Presentation/Sources/CompanySearch/Components/Cell/CompanySearchTableViewCell.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Home/Components/CareerNavigationView.swift, Projects/Presentation/Sources/Home/HomeViewController.swift, Projects/Presentation/Sources/Home/HomeViewModel.swift, Projects/Presentation/Sources/Notice/Cell/NoticeTableViewCell.swift, Projects/Presentation/Sources/Notice/NoticeViewController.swift
>CompanySearch 퍼블리싱
>CompanySearch API 연동
- CompanySearch 퍼블리싱
- CompanySearch API 연동
=> 🔗 :: (#181) CompanySearch 퍼블리싱 API

Projects/Presentation/Sources/Notice/NoticeViewController.swift, Projects/Presentation/Sources/Recruitment/Cell/RecruitmentTableViewCell.swift, Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
>RecruitmentList 디자인 수정
- RecruitmentList 디자인 수정
=> 🔗 :: (#187) Recruitment Design Edit

Projects/Data/Sources/DI/DataSourceAssembly.swift, Projects/Data/Sources/DI/RepositoryAssembly.swift, Projects/Data/Sources/DI/UseCaseAssembly.swift, Projects/Data/Sources/DTO/Notifications/NotificationListDTO.swift, Projects/Data/Sources/DataSource/API/NotificationsAPI.swift, Projects/Data/Sources/DataSource/Remote/RemoteNotificationsDataSource.swift, Projects/Data/Sources/Repositories/NotificationsRepositoryImpl.swift, Projects/Domain/Sources/Entities/Notifications/NotificationEntity.swift, Projects/Domain/Sources/Repositories/NotificationsRepository.swift, Projects/Domain/Sources/UseCases/Notifications/FetchNotificationListUseCase.swift, Projects/Domain/Sources/UseCases/Notifications/ReadNotificationUseCase.swift, Projects/Modules/AppNetwork/Sources/JobisAPI.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift, Projects/Presentation/Sources/Home/Alarm/AlarmViewModel.swift, Projects/Presentation/Sources/Home/Alarm/Cell/AlarmTableViewCell.swift
=> 🔗 :: (#199) 알림 api 연동

ci_scripts/ci_install_tuist.sh, ci_scripts/ci_post_clone.sh
=> 🔗 :: CI Script 수정

Projects/Data/Sources/DTO/Recruitments/RecruitmentDetailResponseDTO.swift, Projects/Domain/Sources/Entities/Recruitments/RecruitmentDetailEntity.swift, Projects/Presentation/Sources/Recruitment/Cell/RecruitmentTableViewCell.swift, Projects/Presentation/Sources/RecruitmentDetail/Cell/FieldTypeDetailViewCell.swift, Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
=> 🔗  :: 상시 모집 처리

Projects/App/Support/Info.plist
=> 🔗 :: (#214) 가로 회전 막기

Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift, Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
=> 🔗  :: (#216) 모집의뢰서 상세 모집 분야 버그 수정

Projects/Core/Sources/Steps/CompanySearchStep.swift, Projects/Core/Sources/Steps/CompanyStep.swift, Projects/Core/Sources/Steps/HomeStep.swift, Projects/Flow/Sources/Company/CompanyFlow.swift, Projects/Flow/Sources/Home/HomeFlow.swift, Projects/Presentation/Sources/CompanySearch/Cell/CompanyTableViewCell.swift, Projects/Presentation/Sources/CompanySearch/CompanyViewController.swift, Projects/Presentation/Sources/CompanySearch/CompanyViewModel.swift, Projects/Presentation/Sources/DI/PresentationAssembly.swift, Projects/Presentation/Sources/Home/HomeViewController.swift, Projects/Presentation/Sources/Home/HomeViewModel.swift
=> 🔗  :: (#215) 기업 탐색 클래스 명 수정  및 버그 개선

Projects/Modules/DesignSystem/Sources/Alert/AlertBuilder.swift, Projects/Modules/DesignSystem/Sources/Alert/AlertButton.swift, Projects/Modules/DesignSystem/Sources/Alert/AlertButtonStyle.swift, Projects/Modules/DesignSystem/Sources/Alert/JobisAlertViewController.swift, Projects/Presentation/Sources/MyPage/MyPageViewController.swift, Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
=> 🔗 :: (#217) 커스텀 Alert

Projects/Domain/Sources/Enums/DepartmentType.swift
=> 🔗 :: (#232) 임베디드소프트웨어개발과 - > 임베디드소프트웨어과

Projects/Domain/Sources/Enums/DepartmentType.swift
=> 🔗 :: (#236) 인공지능소프트웨어개발과 -> 인공지능소프트웨어과

README.md
=> 🔗 :: (#242) Readme 수정

.package.resolved, Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift, Projects/Modules/DesignSystem/Resources/Colors/Sub.xcassets/SkyBlue 30.colorset/Contents.json, Projects/Modules/DesignSystem/Sources/Color/UIColor+Sub.swift, Projects/Modules/DesignSystem/Sources/Typography/JobisFont.swift, Projects/Modules/DesignSystem/Sources/Typography/JobisFontStyle.swift, Projects/Modules/DesignSystem/Sources/UITabBarItem/JobisTabBarItem.swift, Projects/Modules/ThirdPartyLib/Project.swift, Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift, Projects/Presentation/Sources/Home/EmployStatus/Components/LegendView.swift, Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift, Tuist/Dependencies.swift
- ChartView 구현
- DGCharts 라이브러리 추가
- Pie Chart 구현
=> 🔗 :: (#269) ChartView 구현

Projects/Modules/DesignSystem/Sources/Typography/JobisFont.swift, Projects/Modules/DesignSystem/Sources/Typography/JobisFontStyle.swift, Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift, Projects/Presentation/Sources/Home/EmployStatus/Components/ClassButton.swift, Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift
반 별 취업 현황 보기 버튼 퍼블리싱
- 반 별 버튼 component 구현
- EmployStatusViewController ScrollView
=> 🔗 :: (#273) 반 별 취업 현황 보기 버튼

Projects/Presentation/Sources/Apply/ApplyViewModel.swift
지원하기 버튼 활성화 오류 해결
- URL과 파일을 모두 넣어야만 지원 가능하게 변경
=> 🔗 :: (#280) 지원하기 버튼 활성화 오류 해결

Projects/Data/Sources/DTO/Notice/NoticeDetailResponseDTO.swift, Projects/Domain/Sources/Enums/AttachmentType.swift, Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift, Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift
- 공지사항 오류 해결
- 공지사항 오류 해결, 취업률 소수점으로 수정
=> 🔗 :: (#283) 공지사항 오류 수정
